version: '3.8'
services:
  nginx:
    container_name: mynginx
    image: mynginx:latest
    ports:
      - "80:80"
    networks:
      pnet:
        ipv4_address: 192.168.55.101

  django:
    container_name: mydjango
    image: mydjango:latest
    depends_on:
      - djangodb
    environment:
      DB_NAME: djangodb
      DB_USER: jj
      DB_PASSWORD: mjrude1212
      DB_HOST: djangodb
      DB_PORT: 5432
    networks:
      pnet:
        ipv4_address: 192.168.55.102

  laravel:
    container_name: mylaravel
    image: mylaravel:latest
    environment:
      DB_CONNECTION: mysql
      DB_HOST: laraveldb
      DB_PORT: 3306
      DB_DATABASE: laraveldb
      DB_USERNAME: jj
      DB_PASSWORD: mjrude1212
    networks:
      pnet:
        ipv4_address: 192.168.55.103

  djangodb:
    container_name: djangodb
    image: postgres:latest
    volumes:
      - postgresqldb:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: jj
      POSTGRES_PASSWORD: mjrude1212
      POSTGRES_DB: djangodb
    networks:
      pnet:
       ipv4_address: 192.168.55.104
    expose:
      - '5432'

  laraveldb:
    container_name: laraveldb
    image: mysql:latest
    volumes:
      - mysqldb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'laraveldb'
      MYSQL_USER: 'jj'
      MYSQL_PASSWORD: 'mjrude1212'
      MYSQL_ROOT_PASSWORD: 'mjrude1212'
    networks:
      pnet:
        ipv4_address: 192.168.55.105
    expose:
      - '3306'

networks:
  pnet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.55.0/24
    name: pnet

volumes:
  postgresqldb:
  mysqldb:
